[package]
name = "api_basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-mongodb-session = "2.0.0"
tide = "0.16.0"
data_model = { path = "../DataModel/data_model" }