[package]
name = "StorageApi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hmac = "0.12.1"
base64 = "0.13.0"
sha1 = "0.10.1"
url-escape = "0.1.1"
urlqstring = "0.3.5"