[package]
name = "sso_api"
version = "0.1.0"
edition = "2021"
authors = ["lihe07"]
description = "SSO API"


[dependencies]
tide = "0.16.0"
data_model = { path = "../DataModel/data_model" }
api_basics = { path = "../ApiBasics" }
async-std = "1.11.0"
